const List<String> lessons = [
  "FDSC1 – What is Flutter",
  "FDSC2 – Why Flutter",
  "FDSC3 – Applications built with Flutter",
  "FDSC4 – What is Dart",
  "FDSC5 – Dart vs Other Languages",
  "FDSC6 – Tools and Environment Setup",
  "FDSC7 – What are Variables",
  "FDSC8 – Declaring and Initializing Variables",
  "FDSC9 – Types of Variables in Dart (final, const, var)",
  "FDSC10 – Variables (Overview)",
  "FDSC11 – Basic Datatypes (int, double, num, String, bool)",
  "FDSC12 – Operands and Operators",
  "FDSC13 – Arithmetic Operators",
  "FDSC14 – Relational Operators",
  "FDSC15 – Logical Operators",
  "FDSC16 – Assignment Operators",
  "FDSC17 – Unary Operators",
  "FDSC18 – Bitwise Operators",
  "FDSC19 – Conditional / Ternary Operators",
  "FDSC20 – Control Flow in Programming",
  "FDSC21 – If Statement",
  "FDSC22 – If-Else Statement",
  "FDSC23 – If-Else Ladder",
  "FDSC24 – Switch Case",
  "FDSC25 – Need of Looping",
  "FDSC26 – For Loop",
  "FDSC27 – While Loop",
  "FDSC28 – Do-While Loop",
  "FDSC29 – Control Transfer Statements (break, continue)",
  "FDSC30 – Introduction to Functions",
  "FDSC31 – Types of Functions",
  "FDSC32 – Parameters in Functions",
  "FDSC33 – Anonymous Functions",
  "FDSC34 – Higher Order Functions",
  "FDSC35 – Introduction to OOP in Dart",
  "FDSC36 – Defining Classes and Objects",
  "FDSC37 – Creating Objects from Classes",
  "FDSC38 – Default Constructor",
  "FDSC39 – Parameterized Constructor",
  "FDSC40 – Named Constructor",
  "FDSC41 – Constant Constructor",
  "FDSC42 – Constant Constructor (Advanced)",
  "FDSC43 – Types of Inheritance",
  "FDSC44 – Method Overriding",
  "FDSC45 – Abstract Classes",
  "FDSC46 – Using Classes as Interfaces",
  "FDSC47 – Extends vs Implements",
  "FDSC48 – Mixins in Dart",
  "FDSC49 – Extensions in Dart",
  "FDSC50 – Getters and Setters",
  "FDSC51 – Defining Getters and Setters",
  "FDSC52 – Introduction to Enums",
  "FDSC53 – Declaring Enums",
  "FDSC54 – Introduction to Typedefs",
  "FDSC55 – Function Typedefs",
  "FDSC56 – Null Safety",
  "FDSC57 – Nullable vs Non-nullable Types",
  "FDSC58 – Benefits of Null Safety",
  "FDSC59 – Synchronous vs Asynchronous Programming",
  "FDSC60 – Asynchronous Functions",
  "FDSC61 – Future Class",
  "FDSC62 – Async Keyword",
  "FDSC63 – Await Keyword",
  "FDSC64 – Try-Catch with Async/Await",
  "FDSC65 – Error Handling Best Practices",
  "FDSC66 – Introduction to Streams",
  "FDSC67 – Types of Streams",
  "FDSC68 – StreamController",
  "FDSC69 – StreamBuilder",
  "FDSC70 – Flutter Project Structure",
  "FDSC71 – Flutter CLI Commands",
  "FDSC72 – Debugging Tools in Flutter",
  "FDSC73 – Hot Reload vs Hot Restart",
  "FDSC74 – When to Use Hot Reload vs Hot Restart",
  "FDSC75 – Advantages of Hot Reload",
  "FDSC76 – What is a Widget",
  "FDSC77 – Types of Widgets",
  "FDSC78 – Stateless vs Stateful Widget",
  "FDSC79 – Lifecycle of StatefulWidget",
  "FDSC80 – Basic Widgets (Text, Image, Icon, Button, Chip)",
  "FDSC81 – TextField and Input Widgets",
  "FDSC82 – Form and Form Validation",
  "FDSC83 – GestureDetector and InkWell",
  "FDSC84 – AppBar, FAB, SnackBar",
  "FDSC85 – Row, Column, Stack, Align",
  "FDSC86 – Container, Padding, Margin, SizedBox",
  "FDSC87 – Expanded, Flexible, Spacer",
  "FDSC88 – ListView, GridView, PageView",
  "FDSC89 – MediaQuery and LayoutBuilder",
  "FDSC90 – Responsive Layouts",
  "FDSC91 – Shared Preferences",
  "FDSC92 – Hive",
  "FDSC93 – Sqflite",
  "FDSC94 – Reading and Writing Local Data",
  "FDSC95 – Persisting User Sessions",
  "FDSC96 – REST API Basics",
  "FDSC97 – HTTP Requests (http, dio)",
  "FDSC98 – JSON Parsing and Models",
  "FDSC99 – API Error Handling",
  "FDSC100 – Loading States and Feedback",
  "FDSC101 – ChangeNotifier",
  "FDSC102 – Consumer and context.watch",
  "FDSC103 – Theme Switching & Auth Flow",
  "FDSC104 – Streams, Events, States",
  "FDSC105 – Cubit vs Bloc",
  "FDSC106 – BlocProvider, BlocBuilder",
  "FDSC107 – State Handling for APIs",
  "FDSC108 – Firebase Setup",
  "FDSC109 – Firebase Authentication",
  "FDSC110 – Cloud Firestore CRUD",
  "FDSC111 – Firebase Storage",
  "FDSC112 – Firebase Messaging",
  "FDSC113 – Razorpay Integration",
  "FDSC114 – Stripe Integration",
  "FDSC115 – Payment Callbacks",
  "FDSC116 – Secure Payment Flow",
  "FDSC117 – Unit Testing",
  "FDSC118 – Widget Testing",
  "FDSC119 – Integration Testing",
  "FDSC120 – Build APK & AAB",
  "FDSC121 – Play Store Deployment",
  "FDSC122 – iOS Deployment",
  "FDSC123 – AI, ML, DL, NLP",
  "FDSC124 – Cloud vs On-device AI",
  "FDSC125 – AI in Mobile Apps",
  "FDSC126 – AI Packages for Flutter",
  "FDSC127 – API Access Setup",
  "FDSC128 – Sending Prompts",
  "FDSC129 – Streaming Responses",
  "FDSC130 – AI Use Cases",
  "FDSC131 – Image Labeling",
  "FDSC132 – Object Detection",
  "FDSC133 – Face Detection",
  "FDSC134 – Text Recognition (OCR)",
  "FDSC135 – MLKit / TFLite Models",
  "FDSC136 – Speech to Text",
  "FDSC137 – Text to Speech",
  "FDSC138 – Speech + Generative AI",
  "FDSC139 – TensorFlow Lite Basics",
  "FDSC140 – Convert Models to TFLite",
  "FDSC141 – TFLite Inference",
  "FDSC142 – Run TFLite in Flutter",
  "FDSC143 – AI Chatbot",
  "FDSC144 – Voice Assistant",
  "FDSC145 – OCR Scanner with AI",
  "FDSC146 – Smart Camera",
  "FDSC147 – AI Search / Autocomplete",
  "FDSC148 – Recommender Systems",
  "FDSC149 – On-device vs Cloud AI",
  "FDSC150 – Optimizing TFLite Models",
  "FDSC151 – Securing AI APIs",
  "FDSC152 – Caching AI Responses",
  "FDSC153 – Ethical Use of AI",
];
