const List<String> lessons = [
  "FDSC1 – What is Flutter",
  "FDSC2 – Why Flutter",
  "FDSC3 – Applications built with Flutter",
  "FDSC4 – What is Dart",
  "FDSC5 – Dart vs Other Languages",
  "FDSC6 – Tools and Environment Setup",
  "FDSC7 – What are Variables",
  "FDSC8 – Declaring and Initializing Variables",
  "FDSC9 – Types of Variables in Dart (final, const, var)",
  "FDSC10 – Variables (Overview)",
  "FDSC11 – Basic Datatypes (int, double, num, String, bool)",
  "FDSC12 – Operands and Operators",
  "FDSC13 – Arithmetic Operators",
  "FDSC14 – Relational Operators",
  "FDSC15 – Logical Operators",
  "FDSC16 – Assignment Operators",
  "FDSC17 – Unary Operators",
  "FDSC18 – Bitwise Operators",
  "FDSC19 – Conditional / Ternary Operators",
  "FDSC20 – Control Flow in Programming",
  "FDSC21 – If Statement",
  "FDSC22 – If-Else Statement",
  "FDSC23 – If-Else Ladder",
  "FDSC24 – Switch Case",
  "FDSC25 – Need of Looping",
  "FDSC26 – For Loop",
  "FDSC27 – While Loop",
  "FDSC28 – Do-While Loop",
  "FDSC29 – Control Transfer Statements (break, continue)",
  "FDSC30 – Introduction to Functions",
  "FDSC31 – Types of Functions",
  "FDSC32 – Parameters in Functions",
  "FDSC33 – Anonymous Functions",
  "FDSC34 – Higher Order Functions",
  "FDSC35 – Introduction to OOP in Dart",
  "FDSC36 – Defining Classes and Objects",
  "FDSC37 – Creating Objects from Classes",
  "FDSC38 – Default Constructor",
  "FDSC39 – Parameterized Constructor",
  "FDSC40 – Named Constructor",
  "FDSC41 – Constant Constructor",
  "FDSC42 – Constant Constructor (Advanced)",
  "FDSC43 – Types of Inheritance",
  "FDSC44 – Method Overriding",
  "FDSC45 – Abstract Classes",
  "FDSC46 – Using Classes as Interfaces",
  "FDSC47 – Extends vs Implements",
  "FDSC48 – Mixins in Dart",
  "FDSC49 – Extensions in Dart",
  "FDSC50 – Getters and Setters",
  "FDSC51 – Defining Getters and Setters",
  "FDSC52 – Introduction to Enums",
  "FDSC53 – Declaring Enums",
  "FDSC54 – Introduction to Typedefs",
  "FDSC55 – Function Typedefs",
  "FDSC56 – Null Safety",
  "FDSC57 – Nullable vs Non-nullable Types",
  "FDSC58 – Benefits of Null Safety",
  "FDSC59 – Synchronous vs Asynchronous Programming",
  "FDSC60 – Asynchronous Functions",
  "FDSC61 – Future Class",
  "FDSC62 – Async Keyword",
  "FDSC63 – Await Keyword",
  "FDSC64 – Try-Catch with Async/Await",
  "FDSC65 – Error Handling Best Practices",
  "FDSC66 – Introduction to Streams",
  "FDSC67 – Types of Streams",
  "FDSC68 – StreamController",
  "FDSC69 – StreamBuilder",
  "FDSC70 – Flutter Project Structure",
  "FDSC71 – Flutter CLI Commands",
  "FDSC72 – Debugging Tools in Flutter",
  "FDSC73 – Hot Reload vs Hot Restart",
  "FDSC74 – When to Use Hot Reload vs Hot Restart",
  "FDSC75 – Advantages of Hot Reload",
  "FDSC76 – What is a Widget",
  "FDSC77 – Types of Widgets",
  "FDSC78 – Stateless vs Stateful Widget",
  "FDSC79 – Lifecycle of StatefulWidget",
  "FDSC80 – Basic Widgets (Text, Image, Icon, Button, Chip)",
  "FDSC81 – TextField and Input Widgets",
  "FDSC82 – Form and Form Validation",
  "FDSC83 – GestureDetector and InkWell",
  "FDSC84 – AppBar, FAB, SnackBar",
  "FDSC85 – Row, Column, Stack, Align",
  "FDSC86 – Container, Padding, Margin, SizedBox",
  "FDSC87 – Expanded, Flexible, Spacer",
  "FDSC88 – ListView, GridView, PageView",
  "FDSC89 – MediaQuery and LayoutBuilder",
  "FDSC90 – Responsive Layouts",
  "FDSC91 – Shared Preferences",
  "FDSC92 – Hive",
  "FDSC93 – Sqflite",
  "FDSC94 – Reading and Writing Local Data",
  "FDSC95 – Persisting User Sessions",
  "FDSC96 – REST API Basics",
  "FDSC97 – HTTP Requests (http, dio)",
  "FDSC98 – JSON Parsing and Models",
  "FDSC99 – API Error Handling",
  "FDSC100 – Loading States and Feedback",
  "FDSC101 – ChangeNotifier",
  "FDSC102 – Consumer and context.watch",
  "FDSC103 – Theme Switching & Auth Flow",
  "FDSC104 – Streams, Events, States",
  "FDSC105 – Cubit vs Bloc",
  "FDSC106 – BlocProvider, BlocBuilder",
  "FDSC107 – State Handling for APIs",
  "FDSC108 – Firebase Setup",
  "FDSC109 – Firebase Authentication",
  "FDSC110 – Cloud Firestore CRUD",
  "FDSC111 – Firebase Storage",
  "FDSC112 – Firebase Messaging",
  "FDSC113 – Razorpay Integration",
  "FDSC114 – Stripe Integration",
  "FDSC115 – Payment Callbacks",
  "FDSC116 – Secure Payment Flow",
  "FDSC117 – Unit Testing",
  "FDSC118 – Widget Testing",
  "FDSC119 – Integration Testing",
  "FDSC120 – Build APK & AAB",
  "FDSC121 – Play Store Deployment",
  "FDSC122 – iOS Deployment",
  "FDSC123 – AI, ML, DL, NLP",
  "FDSC124 – Cloud vs On-device AI",
  "FDSC125 – AI in Mobile Apps",
  "FDSC126 – AI Packages for Flutter",
  "FDSC127 – API Access Setup",
  "FDSC128 – Sending Prompts",
  "FDSC129 – Streaming Responses",
  "FDSC130 – AI Use Cases",
  "FDSC131 – Image Labeling",
  "FDSC132 – Object Detection",
  "FDSC133 – Face Detection",
  "FDSC134 – Text Recognition (OCR)",
  "FDSC135 – MLKit / TFLite Models",
  "FDSC136 – Speech to Text",
  "FDSC137 – Text to Speech",
  "FDSC138 – Speech + Generative AI",
  "FDSC139 – TensorFlow Lite Basics",
  "FDSC140 – Convert Models to TFLite",
  "FDSC141 – TFLite Inference",
  "FDSC142 – Run TFLite in Flutter",
  "FDSC143 – AI Chatbot",
  "FDSC144 – Voice Assistant",
  "FDSC145 – OCR Scanner with AI",
  "FDSC146 – Smart Camera",
  "FDSC147 – AI Search / Autocomplete",
  "FDSC148 – Recommender Systems",
  "FDSC149 – On-device vs Cloud AI",
  "FDSC150 – Optimizing TFLite Models",
  "FDSC151 – Securing AI APIs",
  "FDSC152 – Caching AI Responses",
  "FDSC153 – Ethical Use of AI",
];
const List<String> flutterRoadmap = [
  // -------------------- MONTH 1 (FOUNDATION) --------------------
  "M1-D1 – What is Flutter & Setup",
  "M1-D2 – Dart Basics (Variables, Data Types)",
  "M1-D3 – Operators & Control Flow",
  "M1-D4 – Loops & Functions",
  "M1-D5 – OOP in Dart",
  "M1-D6 – Null Safety",
  "M1-D7 – Mini Practice App",

  "M1-D8 – What is Widget",
  "M1-D9 – Stateless vs Stateful",
  "M1-D10 – Basic Widgets (Text, Image, Icon)",
  "M1-D11 – Layout (Row, Column)",
  "M1-D12 – Container, Padding, SizedBox",
  "M1-D13 – ListView & GridView",
  "M1-D14 – Mini UI Project",

  "M1-D15 – Navigation (push/pop)",
  "M1-D16 – Named Routes",
  "M1-D17 – Passing Data Between Screens",
  "M1-D18 – Forms & Validation",
  "M1-D19 – Input Fields",
  "M1-D20 – SnackBar, Dialog",
  "M1-D21 – Project: Login UI",

  "M1-D22 – Responsive Design",
  "M1-D23 – MediaQuery",
  "M1-D24 – LayoutBuilder",
  "M1-D25 – Theming",
  "M1-D26 – Dark Mode",
  "M1-D27 – UI Polishing",
  "M1-D28 – Project: Responsive App",

  // -------------------- MONTH 2 (INTERMEDIATE) --------------------
  "M2-D1 – HTTP Requests",
  "M2-D2 – JSON Parsing",
  "M2-D3 – API Integration",
  "M2-D4 – Error Handling",
  "M2-D5 – Loading States",
  "M2-D6 – Project: API App",
  "M2-D7 – Review",

  "M2-D8 – Local Storage (SharedPreferences)",
  "M2-D9 – Hive Database",
  "M2-D10 – Sqflite Basics",
  "M2-D11 – Persisting Data",
  "M2-D12 – Offline Storage",
  "M2-D13 – Project: Notes App",
  "M2-D14 – Review",

  "M2-D15 – Provider State Management",
  "M2-D16 – ChangeNotifier",
  "M2-D17 – Consumer & Context",
  "M2-D18 – App State Design",
  "M2-D19 – Project: Todo App",
  "M2-D20 – Review",
  "M2-D21 – Buffer Day",

  "M2-D22 – Firebase Setup",
  "M2-D23 – Firebase Auth",
  "M2-D24 – Firestore CRUD",
  "M2-D25 – Firebase Storage",
  "M2-D26 – Push Notifications",
  "M2-D27 – Project: Auth App",
  "M2-D28 – Review",

  // -------------------- MONTH 3 (ADVANCED CORE) --------------------
  "M3-D1 – Advanced Navigation (GoRouter)",
  "M3-D2 – Deep Linking",
  "M3-D3 – Animations (Implicit)",
  "M3-D4 – AnimationController",
  "M3-D5 – Hero Animations",
  "M3-D6 – Lottie Animations",
  "M3-D7 – Animation Project",

  "M3-D8 – Bloc Basics",
  "M3-D9 – Cubit vs Bloc",
  "M3-D10 – BlocBuilder",
  "M3-D11 – Bloc Architecture",
  "M3-D12 – API + Bloc",
  "M3-D13 – Project: Clean API App",
  "M3-D14 – Review",

  "M3-D15 – Riverpod",
  "M3-D16 – Comparing State Management",
  "M3-D17 – Best Practices",
  "M3-D18 – Large App State",
  "M3-D19 – Project Refactor",
  "M3-D20 – Review",
  "M3-D21 – Buffer",

  "M3-D22 – Clean Architecture",
  "M3-D23 – MVC vs MVVM",
  "M3-D24 – Repository Pattern",
  "M3-D25 – Use Cases",
  "M3-D26 – Dependency Injection (get_it)",
  "M3-D27 – Scalable Structure",
  "M3-D28 – Project: Production App Structure",

  // -------------------- MONTH 4 (REAL-WORLD) --------------------
  "M4-D1 – Advanced API (Token, JWT)",
  "M4-D2 – Interceptors",
  "M4-D3 – Pagination",
  "M4-D4 – Caching",
  "M4-D5 – Offline-first",
  "M4-D6 – Project",
  "M4-D7 – Review",

  "M4-D8 – Performance Optimization",
  "M4-D9 – Avoid Rebuilds",
  "M4-D10 – DevTools",
  "M4-D11 – Memory Optimization",
  "M4-D12 – List Optimization",
  "M4-D13 – Performance Project",
  "M4-D14 – Review",

  "M4-D15 – Security",
  "M4-D16 – Secure Storage",
  "M4-D17 – API Security",
  "M4-D18 – Firebase Rules",
  "M4-D19 – Data Protection",
  "M4-D20 – Review",
  "M4-D21 – Buffer",

  "M4-D22 – Platform Channels",
  "M4-D23 – Camera & GPS",
  "M4-D24 – Permissions",
  "M4-D25 – Background Tasks",
  "M4-D26 – Native Integration",
  "M4-D27 – Project",
  "M4-D28 – Review",

  // -------------------- MONTH 5 (JOB READY) --------------------
  "M5-D1 – Testing (Unit)",
  "M5-D2 – Widget Testing",
  "M5-D3 – Integration Testing",
  "M5-D4 – Mock APIs",
  "M5-D5 – Test Coverage",
  "M5-D6 – Review",
  "M5-D7 – Buffer",

  "M5-D8 – CI/CD",
  "M5-D9 – GitHub Actions",
  "M5-D10 – Build Automation",
  "M5-D11 – Fastlane",
  "M5-D12 – Deployment",
  "M5-D13 – Play Store",
  "M5-D14 – Review",

  "M5-D15 – Final Project Planning",
  "M5-D16 – Build Full App",
  "M5-D17 – Continue",
  "M5-D18 – Continue",
  "M5-D19 – Continue",
  "M5-D20 – Polish UI",
  "M5-D21 – Fix Bugs",

  "M5-D22 – Portfolio Creation",
  "M5-D23 – Resume",
  "M5-D24 – GitHub Optimization",
  "M5-D25 – Mock Interviews",
  "M5-D26 – Apply Jobs",
  "M5-D27 – Freelance Setup",
  "M5-D28 – Launch 🚀",
];
const List<String> uiuxRoadmap = [
  "UI-1 – UI vs UX Basics",
  "UI-2 – Design Principles",
  "UI-3 – Color Theory",
  "UI-4 – Typography",
  "UI-5 – Spacing & Layout",

  "UI-6 – Figma Basics",
  "UI-7 – Auto Layout",
  "UI-8 – Components",
  "UI-9 – Design Systems",
  "UI-10 – Responsive Design",

  "UI-11 – Mobile Design Patterns",
  "UI-12 – Forms & Inputs",
  "UI-13 – Navigation Design",
  "UI-14 – Error & Empty States",
  "UI-15 – Micro Interactions",

  "UI-16 – Wireframing",
  "UI-17 – Prototyping",
  "UI-18 – User Flow",
  "UI-19 – UX Research Basics",
  "UI-20 – Usability Testing",

  "UI-21 – Portfolio Design",
  "UI-22 – Case Study",
  "UI-23 – Real App Redesign",
];
const List<String> extraSkills = [
  "EX-1 – Git & GitHub",
  "EX-2 – Clean Code Practices",
  "EX-3 – Debugging Skills",
  "EX-4 – Problem Solving (DSA Basics)",

  "EX-5 – REST API Understanding",
  "EX-6 – JSON & Backend Basics",
  "EX-7 – MVC / MVVM Concepts",

  "EX-8 – Firebase (Deep Knowledge)",
  "EX-9 – Authentication Systems",
  "EX-10 – Payment Integration",

  "EX-11 – UI to Code Conversion",
  "EX-12 – Reading Documentation",
  "EX-13 – Using Pub.dev Packages",

  "EX-14 – Communication Skills",
  "EX-15 – Interview Preparation",
];
